### ISSUE TITLE
error: 'move' is not a member of 'stdlib'

### ISSUE THREAD

**Issue by BotiKis** [Pharap/SimpleArduinoUtilitiesAlpha2#2]
When building a arduboy project with platform io it throws a dozen of errors with:
```
src/Deque.h: In member function 'bool Deque<Type, Capacity>::prepend(const ValueType&)':
src/Deque.h:265:21: error: 'move' is not a member of 'stdlib'
```

Sadly I don't know nothing about this to help.

**Comment by Pharap** [comment]
Does this branch fix the problem?

https://github.com/Pharap/SimpleArduinoUtilitiesAlpha2/tree/fix-missing-reference
